print("MY ROUTINE OF THE DAY")
print("I WAKE UP AT 9 AM")
print("i ATTEND MY AI CLASS")
print("I TAKE A BATH AND BRUSH MY TEETH AND GET REDY TILL 11 AM")
print("THEN I EAT MY FOOD")
print("THEN I GO TO MY GUITAR CLASS")
print("then i wathch tv")
print("then i have lunch ")
print("then i play games with my sister")
print("THEN I GO TO MY TUETION FOR 2 HOURS")
print("them i go our to play")
print("then i have dinner and sleep")